### Register new client successfully
POST http://localhost:3000/register
Content-Type: application/json

{
  "email" : "testmail@mail.com",
  "username" : "tester",
  "password" : "123456"
}

### Register new client with invalid email format (check validator is working)
POST http://localhost:3000/register
Content-Type: application/json

{
  "email" : "wrongemail",
  "username" : "any-given-username",
  "password" : "123456"
}

### Login existing client
POST http://localhost:3000/login
Content-Type: application/json

{
  "email" : "test@testmail.com",
  "password" : "123456"
}

### Get an existing client
GET http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWE3NDU5YTQ0YzMyMTc0NWVkN2UwNiIsImlhdCI6MTYwNTAwNjU5M30.C-twCG0sFIbm-S17El3N1GCfjW3a34RpSGG2dBLzzPU
Content-Type: application/json

### Update existing client
PATCH http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWE3NDU5YTQ0YzMyMTc0NWVkN2UwNiIsImlhdCI6MTYwNTAwNjU5M30.C-twCG0sFIbm-S17El3N1GCfjW3a34RpSGG2dBLzzPU
Content-Type: application/json

{
  "username": "new_username_admin",
  "email": "admin@admin.com",
  "password": "123456"
}

### Update existing client's username and avatar
PATCH http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWE3NDU5YTQ0YzMyMTc0NWVkN2UwNiIsImlhdCI6MTYwNTAwNjU5M30.C-twCG0sFIbm-S17El3N1GCfjW3a34RpSGG2dBLzzPU
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="username"

admin
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="any_filename.png"
Content-Type: image/png

< ./new-profile.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--

### Soft delete existing client
DELETE http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWE3NDU5YTQ0YzMyMTc0NWVkN2UwNiIsImlhdCI6MTYwNTAwNjU5M30.C-twCG0sFIbm-S17El3N1GCfjW3a34RpSGG2dBLzzPU
Content-Type: application/json

### Get all purchase history (use API secret instead of JWT)
GET http://localhost:3000/purchase
Authorization: Bearer 928e9861d5f1d573801e4dfd6178f55be55932627ac761944b8a66cbc7c95449
Content-Type: application/json

### Get purchase history by client id (use API secret instead of JWT)
GET http://localhost:3000/purchase/5faa745aa44c321745ed7e07
Authorization: Bearer 928e9861d5f1d573801e4dfd6178f55be55932627ac761944b8a66cbc7c95449
Content-Type: application/json

### Register new purchase by client
POST http://localhost:3000/purchase
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYWE3NDVhYTQ0YzMyMTc0NWVkN2UwNyIsImlhdCI6MTYwNTAyMTgwNH0.ClwBZiDYAEVwvLmSffPtjvpfiS0reykqfA_0IKlGJ0g
Content-Type: application/json

{
  "description" : "Ut bibendum lobortis placerat. Nulla eu cursus nisi. Nullam posuere nec leo vitae commodo. Aenean ac lorem molestie, viverra ipsum non, varius risus. Ut blandit urna fermentum nibh porta, sit amet tincidunt urna consequat. Cras commodo nibh non lacus viverra eleifend. Suspendisse a laoreet mi. Nullam vulputate blandit nulla vel efficitur. In volutpat, diam vitae pharetra tincidunt, est erat rhoncus metus, at mollis nisi lorem et ex. Morbi facilisis sollicitudin varius. Mauris nec quam nisi. Vestibulum pharetra pellentesque tellus vel hendrerit. Duis eu tortor et eros ultricies viverra eu sit amet enim. Sed aliquet risus in ex varius condimentum. Pellentesque ut nunc eu mauris congue pretium. Duis sit amet sollicitudin felis.",
  "price" : 1000000,
  "images" : [
    "https://cdn.pixabay.com/photo/2016/11/18/17/46/architecture-1836070_1280.jpg", "https://cdn.pixabay.com/photo/2018/01/24/15/08/live-3104077_1280.jpg"
  ],
  "services": [
    "Garden",
    "Swimming pool"
  ],
  "location": {
    "latitude": 41.40340,
    "longitude": 2.12772
  },
  "publicationDate": "Nov 7, 2020 12:00:00",
  "propertyType": "Home",
  "homeType": "Penthouse",
  "numBedrooms": "4 or +",
  "numBathrooms": "3 or +",
  "equipment": "Furnished",
  "condition": "New"
}

### Get all properties
GET http://localhost:3000/property
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTcwZDQwNmMyMzEwZmRmZjBjODBlOSIsImlhdCI6MTYwNDg0MzY2NH0.PfE0X8DmzJrI_qjg-tt6xI4LghGVNCdQQ21xEWZgZk8
Content-Type: application/json

### Get newly created properties (last 24h)
GET http://localhost:3000/property/new
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTcwZDQwNmMyMzEwZmRmZjBjODBlOSIsImlhdCI6MTYwNDg0MzY2NH0.PfE0X8DmzJrI_qjg-tt6xI4LghGVNCdQQ21xEWZgZk8
Content-Type: application/json

### Get property details by its "id"
GET http://localhost:3000/property/detail/whateverTheId
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTcwZDQwNmMyMzEwZmRmZjBjODBlOSIsImlhdCI6MTYwNDg0MzY2NH0.PfE0X8DmzJrI_qjg-tt6xI4LghGVNCdQQ21xEWZgZk8
Content-Type: application/json

### Get properties with filters
GET http://localhost:3000/property/filter?propertyType=Home&homeType=Flat/Apartment&numBedrooms=4+or+%2B&numBathrooms=3+or+%2B&equipment=Fully+fitted+kitchen&condition=Good+condition&minPrice=200000&maxPrice=500000&latitudeFrom=41&latitudeTo=42&longitudeFrom=2&longitudeTo=2.2&published=week&services=Lift&services=Garden
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmYTcwZDQwNmMyMzEwZmRmZjBjODBlOSIsImlhdCI6MTYwNDg0MzY2NH0.PfE0X8DmzJrI_qjg-tt6xI4LghGVNCdQQ21xEWZgZk8
Content-Type: application/json